# Halloween Theme - Spooky Orange & Black
# Starship configuration for Rory Terminal Themes

format = """
[‚ï≠‚ï¥](bold bright-black)$os\
$username\
[](bg:color_orange fg:color_bg)\
$directory\
[](fg:color_orange bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_bg)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:color_bg)\
$line_break\
[‚ï∞‚îÄ](bold bright-black)$character"""

palette = 'halloween'

[palettes.halloween]
color_fg = '#ff6b00'
color_bg = '#1a0f00'
color_orange = '#ff8800'
color_yellow = '#ffaa00'
color_red = '#ff0000'

[os]
disabled = false
style = "bg:color_bg fg:color_fg"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
Macos = "Û∞Äµ"
Linux = "Û∞åΩ"

[username]
show_always = true
style_user = "bg:color_bg fg:color_fg"
style_root = "bg:color_bg fg:color_red"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = " "
"Music" = "Û∞ùö "
"Pictures" = " "
"Projects" = "Û∞≤ã "

[git_branch]
symbol = "üéÉ"
style = "bg:color_yellow fg:color_bg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_yellow fg:color_bg"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "üëª"
ahead = "‚á°"
behind = "‚á£"
diverged = "‚áï"
up_to_date = "‚úì"
untracked = "?"
stashed = "üíÄ"
modified = "!"
staged = '[++\($count\)](bg:color_yellow fg:color_bg)'
renamed = "¬ª"
deleted = "üï∑Ô∏è"

[nodejs]
symbol = ""
style = "bg:color_bg fg:color_orange"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:color_bg fg:color_orange"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:color_bg fg:color_orange"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:color_bg fg:color_orange"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "üêç"
style = "bg:color_bg fg:color_orange"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg fg:color_fg"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[‚ñ∂](bold fg:color_fg)'
error_symbol = '[‚ñ∂](bold fg:color_red)'
vimcmd_symbol = '[‚óÄ](bold fg:color_orange)'
vimcmd_replace_one_symbol = '[‚óÄ](bold fg:color_yellow)'
vimcmd_replace_symbol = '[‚óÄ](bold fg:color_yellow)'
vimcmd_visual_symbol = '[‚óÄ](bold fg:color_yellow)'

